name: sync
on:
  push:
    branches:
      - main
jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Mirror the Github repos to Gitee.
        uses: Yikun/hub-mirror-action@master
        with:
          src: 'github/liyipeng123'
          dst: 'gitee/liyipeng3'
          dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
          dst_token: ${{ secrets.GITEE_TOKEN }}
          force_update: true
          static_list: "gone-web"
          debug: true
